# Generated by Django 4.1.9 on 2023-11-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filedata",
            options={"ordering": ("created_at",)},
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_type",
            field=models.CharField(default="application/pdf", max_length=512),
            preserve_default=False,
        ),
    ]
