# Generated by Django 4.1.9 on 2023-11-28 19:49

from django.db import migrations, models
import djcastor.storage


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_fileversion_is_readable_fileversion_is_writable"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="file",
            field=models.FileField(null=True, storage=djcastor.storage.CAStorage(), upload_to="upload"),
        ),
    ]
