# Generated by Django 4.1.9 on 2023-11-28 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_filedata_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filedata",
            old_name="file",
            new_name="cas_location",
        ),
    ]
